use cafe_shop_db

INSERT INTO Product VALUES(N'Cà Phê Sữa Đá',N'Cà Phê Sữa Đá.jpg',N'Cà phê phin kết hợp cũng sữa đặc là một sáng tạo đầy tự hào của người Việt, được xem món uống thương hiệu của Việt Nam.',1);
INSERT INTO Product VALUES(N'Bạc Xỉu',N'Bạc Xỉu.jpg',N'Theo chân những người gốc Hoa đến định cư tại Sài Gòn, Bạc sỉu là cách gọi tắt của "Bạc tẩy xỉu phé" trong tiếng Quảng Đông, chính là: Ly sữa trắng kèm một chút cà phê.',1);
INSERT INTO Product VALUES(N'Caramel Macchiato Đá',N'Caramel Macchiato Đá.jpg',N'Vị thơm béo của sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng, và vị ngọt đậm của sốt caramel.',1);
INSERT INTO Product VALUES(N'Cà Phê Đá Xay-Lạnh',N'Cà Phê Đá Xay-Lạnh.jpg',N'Một phiên bản "upgrade" từ ly cà phê sữa quen thuộc, nhưng lại tỉnh táo và tươi mát hơn bởi lớp đá xay đi kèm. Nhấp 1 ngụm là thấy đã, ngụm thứ hai thêm tỉnh táo và cứ thế lôi cuốn bạn đến giọt cuối cùng.',1);
INSERT INTO Product VALUES(N'Latte Đá',N'Latte Đá.jpg',N'Latte là một sự kết hợp tinh tế giữa lớp nền Espresso hảo hạng và sữa tươi (nhiều hơn so với Cappucino) - mang đến sự cân bằng, nhẹ nhàng trong hương vị.',1);
INSERT INTO Product VALUES(N'Cold Brew Truyền Thống',N'Cold Brew Truyền Thống.jpg',N'Nguyên bản và Tươi mới với hương gỗ thông, hạt dẻ, nốt sô cô la đặc trưng, hương khói nhẹ của hạt Arabica Cầu Đất.',1);
INSERT INTO Product VALUES(N'Cold Brew Sữa Tươi',N'Cold Brew Sữa Tươi.jpg',N'Thanh mát và cân bằng với hương vị cà phê nguyên bản 100% Arabica Cầu Đất cùng sữa tươi thơm béo cho từng ngụm tròn vị, hấp dẫn.',1);
INSERT INTO Product VALUES(N'Americano Nóng',N'Americano Nóng.jpg',N'Americano được pha chế bằng cách thêm nước vào một hoặc hai shot Espresso để pha loãng độ đặc của cà phê, từ đó mang lại hương vị nhẹ nhàng, không gắt mạnh và vẫn thơm nồng nàn.',1);
INSERT INTO Product VALUES(N'Americano Đá',N'Americano Đá.jpg',N'Americano được pha chế bằng cách thêm nước vào một hoặc hai shot Espresso để pha loãng độ đặc của cà phê, từ đó mang lại hương vị nhẹ nhàng, không gắt mạnh và vẫn thơm nồng nàn.',1);
INSERT INTO Product VALUES(N'Cappuccino Nóng',N'Cappuccino Nóng.jpg',N'Cappuccino được gọi vui là thức uống "một-phần-ba" - 1/3 Espresso, 1/3 Sữa nóng, 1/3 Foam.',1);
INSERT INTO Product VALUES(N'Cappuccino Đá',N'Cappuccino Đá.jpg',N'Cappuccino được gọi vui là thức uống "một-phần-ba" - 1/3 Espresso, 1/3 Sữa nóng, 1/3 Foam.',1);
INSERT INTO Product VALUES(N'Caramel Macchiato Nóng',N'Caramel Macchiato Nóng.jpg',N'Vị thơm béo của bọt sữa và sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng, và vị ngọt đậm của sốt caramel.',1);
INSERT INTO Product VALUES(N'Latte Nóng',N'Latte Nóng.jpg',N'Khi chuẩn bị Latte, cà phê Espresso và sữa nóng được trộn lẫn vào nhau, bên trên vẫn là lớp foam nhưng mỏng và nhẹ hơn Cappucinno.',1);
INSERT INTO Product VALUES(N'Mocha Nóng',N'Mocha Nóng.jpg',N'Cà phê Mocha được ví von đơn giản là Sốt Sô cô la được pha cùng một tách Espresso.',1);
INSERT INTO Product VALUES(N'Mocha Đá',N'Mocha Đá.jpg',N'Cà phê Mocha được ví von đơn giản là Sốt Sô cô la được pha cùng một tách Espresso.',1);
INSERT INTO Product VALUES(N'Cà Phê Đen Nóng',N'Cà Phê Đen Nóng.jpg',N'Một tách cà phê đen thơm ngào ngạt, phảng phất mùi cacao là món quà tự thưởng tuyệt vời nhất cho những ai mê đắm tinh chất nguyên bản nhất của cà phê. Một tách cà phê trầm lắng, thi vị giữa dòng đời vồn vã.',1);
INSERT INTO Product VALUES(N'Cà Phê Đen Đá',N'Cà Phê Đen Đá.jpg',N'Một tách cà phê đen thơm ngào ngạt, phảng phất mùi cacao là món quà tự thưởng tuyệt vời nhất cho những ai mê đắm tinh chất nguyên bản nhất của cà phê. Một tách cà phê trầm lắng, thi vị giữa dòng đời vồn vã.',1);
INSERT INTO Product VALUES(N'Cà Phê Sữa Nóng',N'Cà Phê Sữa Nóng.jpg',N'Cà phê phin kết hợp cũng sữa đặc là một sáng tạo đầy tự hào của người Việt, được xem món uống thương hiệu của Việt Nam.',1);
INSERT INTO Product VALUES(N'Espresso Đá',N'Espresso Đá.jpg',N'cà phê máy sử dụng tỷ lệ trộn 70% Arabica và 30% Robusta, cà phê nguyện chất chiết suất từ máy dưới áp suất cao, hương thơm mạnh và chua nhẹ từ hạt, vị đậm đà của hạt robusta, hàm lượng cafein thấp do tính chất của hạt Arabica',1);
INSERT INTO Product VALUES(N'Espresso Nóng',N'Espresso Nóng.jpg',N'Một cốc Espresso nguyên bản được bắt đầu bởi những hạt Arabica chất lượng, phối trộn với tỉ lệ cân đối hạt Robusta, cho ra vị ngọt caramel, vị chua dịu và sánh đặc. Để đạt được sự kết hợp này, chúng tôi xay tươi hạt cà phê cho mỗi lần pha.',1);
INSERT INTO Product VALUES(N'Bạc Xỉu Nóng',N'Bạc Xỉu Nóng.jpg',N'Bạc xỉu nóng',1);
INSERT INTO Product VALUES(N'Cold Brew Phúc Bồn Tử',N'Cold Brew Phúc Bồn Tử.jpg',N'Vị chua ngọt của trái phúc bồn tử, làm dậy lên hương vị trái cây tự nhiên vốn sẵn có trong hạt cà phê, hòa quyện thêm vị đăng đắng, ngọt dịu nhẹ nhàng của Cold Brew mang đến cách thưởng thức cà phê hoàn toàn mới và đầy thú vị.',1);
INSERT INTO Product VALUES(N'Cold Brew Cam Sả',N'Cold Brew Cam Sả.jpg',N'Tươi mát - Mượt mà, là sự kết hợp đầy mới mẻ khi hương vị của cam và sả được cân bằng trên nền của những nốt hương cà phê pha lạnh.',1);

INSERT INTO Product VALUES(N'Phúc Bồn Tử Cam Đá Xay',N'Phúc Bồn Tử Cam Đá Xay.jpg',N'Tê tái ngay đầu lưỡi bởi sự mát lạnh của đá xay. Hòa quyện thêm hương vị chua chua, ngọt ngọt từ trái cam tươi và trái phúc bồn tử 100% tự nhiên, để cho ra một hương vị thanh mát, kích thích vị giác đầy thú vị ngay từ lần đầu thưởng thức.',2);
INSERT INTO Product VALUES(N'Cà Phê Đá Xay-Lạnh',N'Cà Phê Đá Xay-Lạnh.jpg',N'Một phiên bản "upgrade" từ ly cà phê sữa quen thuộc, nhưng lại tỉnh táo và tươi mát hơn bởi lớp đá xay đi kèm. Nhấp 1 ngụm là thấy đã, ngụm thứ hai thêm tỉnh táo và cứ thế lôi cuốn bạn đến giọt cuối cùng.',2);
INSERT INTO Product VALUES(N'Cookie Đá Xay',N'Cookie Đá Xay.jpg',N'Những mẩu bánh cookies giòn rụm kết hợp ăn ý với sữa tươi và kem tươi béo ngọt, đem đến cảm giác lạ miệng gây thích thú. Một món uống phá cách dễ thương.',2);
INSERT INTO Product VALUES(N'Đào Việt Quất Đá Xay',N'Đào Việt Quất Đá Xay.jpg',N'Vẫn vị đào quen thuộc nhưng được khoác lên mình một vẻ đầy thanh mát và giải khát hơn.',2);
INSERT INTO Product VALUES(N'Chocolate Đá Xay',N'Chocolate Đá Xay.jpg',N'Sữa và kem tươi béo ngọt được “cá tính hoá” bởi vị chocolate đăng đắng. Dành cho các tín đồ hảo ngọt. Lựa chọn hàng đầu nếu bạn đang cần chút năng lượng tinh thần để thúc đẩy nhịp sống.',2);
INSERT INTO Product VALUES(N'Matcha Đá Xay',N'Matcha Đá Xay.jpg',N'Matcha thanh, nhẫn, và đắng nhẹ được nhân đôi sảng khoái khi uống lạnh. Nhấn nhá thêm những nét bùi béo của kem và sữa. Gây thương nhớ vô cùng!',2);
INSERT INTO Product VALUES(N'Chanh Sả Đá Xay',N'Chanh Sả Đá Xay.jpg',N'Sự kết hợp giữa chanh, sả thơm lừng và đá đem lại cảm giác mát lạnh xua tan nóng bức của mùa hè.',2);
INSERT INTO Product VALUES(N'Yogurt Dưa Lưới phát tài',N'Yogurt Dưa Lưới phát tài.jpg',N'Vị yogurt chua ngọt, mát lạnh tái tê, quyện cùng dưa lưới thơm lừng thử là mê ngay Giải nhiệt đón Tết thiệt healthy với Yogurt Dưa lưới chua chua ngọt ngọt, thơm lừng đặc trưng, thêm sẵn topping dưa lưới vàng tươi, cho bạn nhâm nhi vui miệng, để chuyện hẹn hò rôm rả thiệt vui. Thưởng thức ngay!',2);

INSERT INTO Product VALUES(N'Trà Phúc Bồn Tử',N'Trà Phúc Bồn Tử.jpg',N'Lần đầu tiên Trà Oolong và trái "Phúc Bồn Tử" hoàn toàn tự nhiên, được kết hợp để tạo ra một dư vị hoàn toàn tươi mới. Nhấp ngay một ngụm là thấy mát lạnh ngay tức khắc, đọng lại mãi nơi cuốn họng là hương vị trà thơm lừng và vị ngọt thanh, chua dịu khó quên của trái phúc bồn tử.',3);
INSERT INTO Product VALUES(N'Trà Đào Cam Sả - Đá',N'Trà Đào Cam Sả - Đá.jpg',N'Vị thanh ngọt của đào Hy Lạp, vị chua dịu của Cam Vàng nguyên vỏ, vị chát của trà đen tươi được ủ mới mỗi 4 tiếng, cùng hương thơm nồng đặc trưng của sả chính là điểm sáng làm nên sức hấp dẫn của thức uống này.',3);
INSERT INTO Product VALUES(N'Oolong Hạt Sen - Nóng',N'Oolong Hạt Sen - Nóng.jpg',N'Trà Oolong Sen nóng sẽ dậy hơn mùi thơm của trà và hạt sen. Trà có vị ngọt dịu nhẹ, rất tốt cho sức khoẻ và giúp giữ ấm cơ thể. Sản phẩm có vị trà nhẹ nhàng vừa phải, có thể dùng được cả cho buổi sáng và chiều tối.',3);
INSERT INTO Product VALUES(N'Oolong Vải - Đá',N'Oolong Vải - Đá.jpg',N'Là sự kết hợp của trà Oolong và trái vải quen thuộc. Là món uống thanh mát, dịu nhẹ rất dễ sử dụng bởi sự hoà quyện của vị chua thanh của vải, hậu vị ngọt kéo dài của trà oolong. Ngoài ra trong mỗi ly nước còn có thêm trái vải dùng kèm. Sản phẩm có vị trà nhẹ nhàng vừa phải, có thể dùng được cả cho buổi sáng và chiều tối.',3);
INSERT INTO Product VALUES(N'Trà Đào Cam Sả - Nóng',N'Trà Đào Cam Sả - Nóng.jpg',N'Vị thanh ngọt của đào Hy Lạp, vị chua dịu của Cam Vàng nguyên vỏ, vị chát của trà đen tươi được ủ mới mỗi 4 tiếng, cùng hương thơm nồng đặc trưng của sả',3);
INSERT INTO Product VALUES(N'Oolong Vải - Nóng',N'Oolong Vải - Nóng.jpg',N'Là sự kết hợp của trà Oolong và trái vải quen thuộc. Nhâm nhi từng ngụm trà nóng khách hàng sẽ trải nghiệm trọn vẹn hơn mùi thơm dậy của vải. Vị ngọt thanh, chua nhẹ của sản phẩm vẫn được giữ nguyên rất dễ uống. Sản phẩm có vị trà nhẹ nhàng vừa phải, có thể dùng được cả cho buổi sáng và chiều tối.',3);
INSERT INTO Product VALUES(N'Oolong Hạt Sen - Đá',N'Oolong Hạt Sen - Đá.jpg',N'Trà Oolong và hạt Sen đều là những thành phần tốt cho sức khoẻ với công dụng thanh lọc cơ thể, giải nhiệt và làm đẹp. Trà Oolong Sen An nhiên có vị thanh mát của trà và sen, vị ngọt dịu kết hợp cùng chút béo thơm của cream cheese và hạt sen tươi mềm ăn kèm. Sản phẩm có vị trà nhẹ nhàng vừa phải, có thể dùng được cả cho buổi sáng và chiều tối.',3);
INSERT INTO Product VALUES(N'Trà Dưa Lưới phú quý',N'Trà Dưa Lưới phú quý.jpg',N'Từng ngụm ngon mê ly từ Dưa lưới thanh mát quyện cùng nền Trà Lài thơm ngon dịu nhẹ. Thanh vị trà mát vị dưa - Sự kết hợp hoàn hảo của nền trà lài nhẹ nhàng, cùng vị dưa lưới đặc trưng, Nhà còn cho sẵn topping dưa lươi vàng tươi để bạn thêm hứng khởi đón Tết thiệt tươi khoẻ, may mắn nhé. Thưởng thức ngay!',3);

INSERT INTO Product VALUES(N'Trà Sữa Mắc Ca Trân Châu Trắng',N'Trà Sữa Mắc Ca Trân Châu Trắng.jpg',N'Đổi vị tươi mới - Vừa ngon vừa khoẻ Mỗi ngày với Nhà sẽ là điều tươi mới hơn với sữa hạt mắc ca thơm ngon, bổ dưỡng quyện cùng nền trà Oolong cho vị cân bằng, ngọt dịu. Trân châu trắng giòn dai được thêm sẵn, mang lại cho bạn cảm giác "đã" trong từng ngụm, thoả cơn thèm trà sữa ngay.',4);
INSERT INTO Product VALUES(N'Trà Đen Macchiato',N'Trà Đen Macchiato.jpg',N'Trà đen được ủ mới mỗi ngày, giữ nguyên được vị chát mạnh mẽ đặc trưng của lá trà, phủ bên trên là lớp Macchiato "homemade" bồng bềnh quyến rũ vị phô mai mặn mặn mà béo béo.',4);
INSERT INTO Product VALUES(N'Matcha Macchiato',N'Matcha Macchiato.jpg',N'Bột trà xanh Matcha thơm lừng hảo hạng cùng lớp Macchiato béo ngậy là một sự kết hợp tuyệt vời.',4);
INSERT INTO Product VALUES(N'Trà Lài Macchiato - Lạnh',N'Trà Lài Macchiato - Lạnh.jpg',N'Ngọt mát tinh tế Ngay ngụm đầu tiên chính là vị beo béo ngọt dịu của lớp macchiato, sau đó được cân bằng lại bởi lớp thanh mát từ nền trà lài dịu nhẹ - 1 hương vị tươi mới cho team hảo ngọt nhưng thích thanh mát.',4);

INSERT INTO Product VALUES(N'Sinh Tố Cam Xoài',N'Sinh Tố Cam Xoài.jpg',N'Vị mứt cam xoài hòa trộn độc đáo với sữa chua, cho cảm giác chua ngọt rất sướng. Điểm nhấn là những mẩu bánh cookie giòn tan giúp sự thưởng thức thêm thú vị.',5);
INSERT INTO Product VALUES(N'Sinh Tố Việt Quất',N'Sinh Tố Việt Quất.jpg',N'Mứt Việt Quất chua thanh, ngòn ngọt, phối hợp nhịp nhàng với dòng sữa chua bổ dưỡng. Là món sinh tố thơm ngon mà cả đầu lưỡi và làn da đều thích.',5);
INSERT INTO Product VALUES(N'Trà Matcha Latte Nóng',N'Trà Matcha Latte Nóng.jpg',N'Với màu xanh mát mắt của bột trà Matcha, vị ngọt nhẹ nhàng, pha trộn cùng sữa tươi và lớp foam mềm mịn, Matcha Latte là thức uống yêu thích của tất cả mọi người khi ghé The Coffee House.',5);
INSERT INTO Product VALUES(N'Trà Matcha Latte Đá',N'Trà Matcha Latte Đá.jpg',N'Với màu xanh mát mắt của bột trà Matcha, vị ngọt nhẹ nhàng, pha trộn cùng sữa tươi và lớp foam mềm mịn, Matcha Latte là thức uống yêu thích của tất cả mọi người khi ghé The Coffee House.',5);
INSERT INTO Product VALUES(N'Socola Đá',N'Socola Đá.jpg',N'Cacao nguyên chất hoà cùng sữa tươi béo ngậy. Vị ngọt tự nhiên, không gắt cổ, để lại một chút đắng nhẹ, cay cay trên đầu lưỡi.',5);

INSERT INTO Product VALUES(N'Mít Sấy',N'Mít Sấy.jpg',N'Mít sấy khô vàng ươm giòn rụm, khi ăn vẫn giữ nguyên được vị ngọt lịm của mít tươi.',6);
INSERT INTO Product VALUES(N'Sô Cô La Gừng',N'Sô Cô La Gừng.jpg',N'Sô cô la cùng gừng dẻo thơm đặc trưng, ngọt ngào và cay dịu - món ăn vặt mới lạ, cho cuộc hẹn hò thêm thú vị tươi mới. Cắn 1 miếng là mê, và nhâm nhi với món nước nào cũng ngon tái tê.',6);
INSERT INTO Product VALUES(N'Bánh Mì Que Pate Cay',N'Bánh Mì Que Pate Cay.jpg',N'Bánh Mì Que Pate Cay',6);
INSERT INTO Product VALUES(N'Bánh Mì Que Pate',N'Bánh Mì Que Pate.jpg',N'Bánh Mì Que Pate',6);

INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(1,35,'M',5,'43000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(2,26,'L',4,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(3,13,'M',3,'23000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(4,51,'M',1,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(5,11,'L',1,'39000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(6,1,'L',3,'53000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(7,52,'L',4,'35000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(8,38,'S',2,'27000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(9,41,'S',4,'31000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(10,29,'S',1,'55000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(11,29,'L',2,'23000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(12,35,'M',5,'49000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(13,11,'S',4,'55000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(14,44,'L',3,'27000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(15,45,'L',2,'27000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(16,42,'M',3,'49000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(17,20,'L',5,'49000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(18,42,'S',5,'49000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(19,6,'L',5,'55000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(20,37,'S',5,'43000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(21,26,'M',2,'51000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(22,27,'S',4,'53000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(23,27,'S',2,'31000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(24,1,'M',3,'47000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(25,22,'L',1,'51000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(26,11,'S',5,'21000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(27,39,'S',1,'41000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(28,3,'L',5,'51000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(29,41,'L',3,'53000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(30,7,'M',3,'49000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(31,4,'M',2,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(32,32,'S',2,'29000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(33,9,'S',1,'31000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(34,6,'L',4,'23000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(35,32,'S',1,'25000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(36,7,'S',1,'31000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(37,50,'S',5,'49000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(38,11,'S',3,'41000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(39,23,'L',1,'37000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(40,30,'M',1,'37000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(41,39,'L',3,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(42,3,'M',5,'29000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(43,10,'S',5,'27000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(44,39,'S',1,'29000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(45,9,'M',4,'41000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(46,41,'L',2,'49000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(47,39,'L',2,'35000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(48,40,'S',3,'47000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(49,17,'L',1,'43000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(50,36,'S',5,'41000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(51,27,'L',5,'23000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(52,52,'L',4,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(53,32,'S',2,'29000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(54,16,'S',4,'35000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(55,1,'L',4,'41000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(56,6,'M',2,'47000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(57,33,'S',2,'21000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(58,50,'L',3,'39000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(59,33,'S',1,'37000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(60,8,'L',3,'51000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(61,25,'S',5,'51000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(62,37,'S',4,'45000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(63,26,'M',5,'35000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(64,22,'M',4,'23000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(65,6,'M',5,'45000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(66,23,'S',4,'43000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(67,16,'L',2,'35000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(68,21,'M',4,'55000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(69,49,'S',1,'19000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(70,45,'M',1,'53000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(71,25,'M',4,'29000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(72,39,'L',3,'41000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(73,32,'S',3,'25000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(74,11,'L',2,'51000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(75,1,'S',3,'41000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(76,16,'M',4,'47000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(77,19,'L',1,'19000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(78,10,'L',1,'55000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(79,27,'L',5,'43000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(80,23,'M',5,'45000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(81,6,'S',5,'43000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(82,6,'S',1,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(83,42,'M',1,'37000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(84,28,'S',2,'45000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(85,43,'M',3,'31000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(86,34,'S',4,'51000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(87,50,'S',5,'49000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(88,15,'M',1,'25000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(89,33,'S',2,'19000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(90,41,'L',2,'37000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(91,15,'L',2,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(92,9,'S',3,'25000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(93,14,'L',4,'53000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(94,16,'S',5,'43000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(95,25,'S',2,'31000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(96,51,'L',5,'49000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(97,21,'L',1,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(98,9,'S',1,'35000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(99,47,'L',3,'53000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(100,42,'S',1,'53000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(84,40,'M',1,'25000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(24,34,'M',1,'41000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(7,44,'L',2,'25000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(83,19,'L',1,'31000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(62,16,'L',2,'41000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(19,41,'S',1,'55000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(58,33,'M',1,'19000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(89,21,'M',3,'53000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(27,18,'S',3,'25000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(12,2,'L',2,'47000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(10,9,'S',2,'37000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(75,21,'M',3,'31000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(18,43,'L',3,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(59,16,'M',2,'41000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(65,41,'S',3,'47000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(13,51,'S',2,'37000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(61,14,'L',2,'27000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(37,22,'L',3,'55000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(66,25,'L',1,'27000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(85,19,'M',3,'23000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(97,8,'L',2,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(72,26,'S',1,'51000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(38,33,'M',3,'31000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(53,14,'L',1,'51000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(37,19,'S',3,'37000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(50,34,'S',2,'19000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(98,18,'L',2,'41000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(53,13,'M',3,'23000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(28,47,'M',2,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(45,44,'L',1,'45000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(40,28,'M',2,'25000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(46,52,'L',1,'23000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(90,33,'S',2,'39000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(71,37,'L',3,'27000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(76,13,'L',1,'53000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(28,49,'L',1,'25000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(77,50,'S',2,'41000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(29,14,'S',3,'21000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(16,22,'S',3,'27000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(5,23,'L',1,'29000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(59,29,'M',2,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(73,34,'M',1,'45000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(25,36,'M',1,'39000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(40,16,'L',2,'19000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(18,13,'S',2,'43000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(90,36,'L',1,'51000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(28,25,'S',2,'39000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(74,48,'L',3,'19000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(30,44,'L',2,'55000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(26,7,'M',2,'39000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(97,21,'L',3,'39000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(30,7,'L',2,'43000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(7,15,'M',3,'35000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(26,48,'M',1,'35000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(39,47,'M',3,'43000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(62,13,'S',3,'27000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(16,18,'M',3,'23000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(33,35,'L',3,'47000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(32,3,'S',2,'27000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(63,36,'S',3,'45000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(63,20,'M',2,'51000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(71,32,'L',1,'53000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(90,10,'S',2,'31000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(53,44,'L',2,'19000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(8,28,'M',3,'41000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(74,28,'L',1,'41000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(99,28,'M',3,'53000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(35,38,'S',2,'27000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(26,44,'M',1,'29000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(41,41,'S',1,'27000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(79,46,'M',2,'31000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(4,7,'L',2,'31000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(2,43,'L',3,'43000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(6,46,'L',2,'37000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(7,32,'M',1,'37000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(13,29,'M',2,'43000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(53,46,'M',1,'19000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(14,8,'M',2,'21000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(68,48,'M',2,'47000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(60,6,'M',2,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(8,3,'S',2,'55000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(55,25,'L',2,'43000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(30,10,'L',1,'31000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(99,24,'L',1,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(30,9,'L',1,'35000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(93,18,'S',1,'21000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(90,41,'S',3,'43000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(14,22,'S',3,'43000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(9,8,'L',1,'45000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(92,48,'L',3,'49000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(77,14,'S',3,'35000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(15,11,'L',2,'55000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(4,14,'M',1,'35000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(9,8,'L',2,'21000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(16,18,'M',3,'55000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(36,2,'L',2,'43000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(60,51,'L',2,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(28,1,'S',1,'23000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(1,24,'L',1,'29000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(3,36,'S',3,'27000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(74,52,'S',3,'37000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(97,50,'S',3,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(84,6,'L',2,'55000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(30,41,'M',1,'49000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(91,24,'L',3,'31000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(6,30,'L',2,'23000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(37,2,'S',2,'53000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(38,12,'L',1,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(93,42,'L',3,'39000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(66,32,'M',3,'55000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(3,45,'S',1,'51000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(50,15,'M',1,'21000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(4,30,'S',1,'23000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(69,30,'L',1,'31000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(48,11,'L',2,'21000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(6,45,'L',2,'31000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(28,18,'L',2,'21000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(40,33,'M',3,'27000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(45,35,'M',2,'31000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(30,26,'S',3,'49000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(11,16,'S',1,'41000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(69,14,'M',3,'47000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(97,28,'M',1,'21000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(8,31,'S',2,'55000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(75,36,'L',3,'39000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(45,15,'L',3,'39000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(95,13,'M',1,'35000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(29,43,'M',3,'47000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(53,29,'S',2,'25000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(65,42,'L',3,'21000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(98,34,'S',1,'37000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(47,29,'L',3,'53000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(62,52,'M',1,'27000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(53,7,'L',3,'49000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(93,32,'L',1,'35000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(19,39,'S',1,'45000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(10,20,'L',3,'47000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(20,19,'L',3,'55000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(58,8,'S',2,'43000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(33,3,'S',2,'27000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(15,34,'S',1,'19000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(81,40,'L',3,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(7,15,'M',2,'35000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(77,9,'M',3,'51000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(71,32,'L',2,'45000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(16,52,'S',3,'23000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(34,24,'S',2,'27000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(21,7,'L',2,'31000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(67,16,'L',1,'49000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(1,23,'M',3,'47000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(3,26,'S',2,'29000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(66,47,'S',1,'23000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(13,17,'S',1,'21000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(77,52,'M',2,'49000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(41,41,'S',2,'41000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(96,2,'S',1,'45000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(79,25,'S',3,'31000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(96,44,'M',1,'39000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(4,21,'L',2,'55000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(20,44,'L',3,'55000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(78,16,'M',3,'47000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(9,39,'S',3,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(66,51,'L',1,'45000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(61,30,'M',1,'29000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(92,12,'L',3,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(96,16,'M',1,'51000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(82,36,'L',1,'51000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(15,33,'M',1,'37000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(87,52,'L',2,'47000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(33,45,'S',2,'45000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(36,43,'M',2,'41000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(10,36,'M',2,'25000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(64,26,'M',1,'23000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(25,47,'M',2,'37000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(88,2,'L',2,'19000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(61,22,'M',1,'35000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(81,16,'L',1,'41000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(27,43,'L',3,'47000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(77,36,'L',2,'19000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(10,23,'M',1,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(30,38,'S',3,'33000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(65,24,'L',3,'29000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(79,34,'S',3,'51000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(18,23,'S',1,'41000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(37,17,'S',1,'55000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(56,15,'L',2,'29000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(27,36,'L',3,'27000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(54,40,'S',2,'25000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(100,47,'L',3,'19000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(96,38,'M',2,'39000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(22,46,'L',2,'53000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(87,20,'S',2,'39000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(54,6,'S',2,'35000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(27,21,'L',2,'49000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(77,18,'S',2,'21000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(1,12,'L',2,'29000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(81,50,'S',1,'35000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(81,51,'L',2,'47000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(1,37,'S',3,'31000');
INSERT INTO ProductInOrder([OrderID],[ProductID],[Size],[Quantity],[Price]) VALUES(99,22,'S',2,'49000');

